name: vocabulary_app
description: "This is a Flutter-based mobile application that replicates the core features of the Vocabulary app, with added UX enhancements and a unique feature. The app includes an onboarding flow, a home page with swipeable words, and haptic feedback for a better user experience."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  circular_progress_button: ^0.0.5
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  haptic_feedback: ^0.5.1+1
  showcaseview: ^4.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#E6E2D8"  # Background color of the splash screen
  image: assets/icon/icon.png  # Path to splash image
  color_dark: "#E6E2D8"
  image_dark: assets/icon/icon.png
  android_12:
    image: assets/icon/icon.png
    color: "#E6E2D8"
    icon_background_color: "#E6E2D8"

flutter_launcher_icons:
  android: false
  ios: true
  adaptive_icon_background: "#E6E2D8"
  adaptive_icon_foreground: assets/icon/icon.png
#  adaptive_icon_foreground_inset: 2
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/icon/vicon.png
    - assets/icon/themes.png
    - assets/ob1.png
    - assets/ob2.png
    - assets/ob3.png
    - assets/photos/sculpture.png
    - assets/photos/nature.png



  fonts:
    - family: DMSerifDisplay
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
        - asset: assets/fonts/DMSerifDisplay-Italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 300
    - family: Bitter
      fonts:
        - asset: assets/fonts/Bitter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Bitter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Bitter-Regular.ttf
          weight: 300
